<TestFunction>:
	MDGridLayout:
		cols: 1
		ScrollView:
			BoxLayout:
				orientation: 'horizontal'
				size_hint_x: 2
				spacing: 10
				MDCard:
					orientation: 'vertical'
					size_hint_y: None
					height: 50
					
					canvas.before:
						Color:
							rgba: 0,0,0,1
						Rectangle:
							size: self.size
							pos: self.pos
							
					MDLabel:
						text: "ok"
				MDCard:
					orientation: 'vertical'
					size_hint_y: None
					height: 50
					
					canvas.before:
						Color:
							rgba: 1,0,0,1
						Rectangle:
							size: self.size
							pos: self.pos
							
					MDLabel:
						text: "ok"
			