<MainFunction>:
	
	MDToolbar:
		id: tool_bar
		top: root.height
		title: "Covid-19 Tracker Malaysia"
	
	MDGridLayout:
		cols: 2
		spacing: root.width /2
		padding: 20
		size_hint_y: None
		top: (root.height - tool_bar.height)
		
		id: statistic_mode
		
		MDFlatButton:
			size_hint: 1,.2
			markup: True
			text: "[b]Global[/b]"
			
			font_size: '20sp'
			
			theme_text_color: 'Custom'
			text_color: (230/255,0,0,1)
			id: global_button
			on_release:
				root.change_statistics(0)
		
		MDFlatButton:
			size_hint: 1,.2
			markup: True
			text: "Local"
			id: local_button
			theme_text_color: 'Custom'
			text_color: 105/255,105/255,105/255,1
			on_release:
				root.change_statistics(1)
		
	
	ScreenManager:
		id: screen_manager
	
		
		Screen:
			name: 'refresh_database'
			
			
			MDSpinner:
				id: refresh_animation
				active: True
			
			
			
			MDIconButton:
				pos_hint: {'center_x': .5, 'center_y':.5}
				user_font_size: '120sp'
				id: refresh_status
				icon: 'database-refresh'
			
			
			
			
		Screen:
			name: 'details_screen'
			
			
			MDGridLayout:
				cols: 1
				padding: 30
				spacing: 20
				pos_hint: {'top':.9}
				id: top_data_detail
				size_hint_y: .3
				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.02
					
					md_bg_color: 72/255,72/255,72/255,1
					
					MDLabel:

						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
						text: "Last Update Data:"
						
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 1,204/255,0,1
						id: last_date
					
				
				
				
				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.02
					
					id: total_detail_card
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:

						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
						text: "Total confirmed cases:"
						
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 1,204/255,0,1
						id: total_detail
					
					


#######################
			MDGridLayout:
				cols: 1
				size_hint_y: 1.2
				FloatLayout:
					ScrollView:
						pos_hint: {'top':.02}
						size_hint_y: None
						top: (root.height - total_detail_card.height) - 130
						BoxLayout:
							size_hint_y: 1
							orientation: 'horizontal'
							size_hint_x: 3.5
							spacing: 30
							padding: 10
							#top: (root.height - total_detail_card.height) - 130
							
							
							
							
							MDCard:
								elevation: 10
								orientation: 'vertical'
								size_hint: 1,1
								
								
								md_bg_color: 72/255,72/255,72/255,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									
									height: self.texture_size[1]
									text: "Total today: "
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 1,0,1,1
									id: total_today_detail
							
							
							
							
							

							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 72/255,72/255,72/255,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									
									text: "Total actives:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 0,102/255,1,1
									id: active_detail

							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 72/255,72/255,72/255,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									

									text: "Total recovered:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 0, 230/255,77/255,1
									id: recovered_detail
										

							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 0,0,0,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									

									text: "Incident Rate:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 1,0,0,1
									id: incident_rate
						
						
						

						
						
#######################
					
#######################								
				FloatLayout:
					ScrollView:
						pos_hint: {'top':.6}
						top: root.height / 2.1
						size_hint_y: None
						BoxLayout:
							orientation: 'horizontal'
							size_hint_x: 3.5
							spacing: 30
							padding: 10
							
						
							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 72/255,72/255,72/255,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									text: "People tested:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 0, 230/255,77/255,1
									id: people_tested
							
						
							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 72/255,72/255,72/255,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									

									text: "Total hospitalized:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 0, 230/255,77/255,1
									id: people_hospitalized
							

						
							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 72/255,72/255,72/255,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									

									text: "Total deaths:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 1, 0,0,1
									id: death_detail
							
							
						
							MDCard:
								orientation: 'vertical'
								size_hint: 1,.8
								
								
								md_bg_color: 0,0,0,1
								
								
								MDLabel:
									
									theme_text_color: 'Custom'
									text_color: 1,1,1,1
									

									text: "Mortality Rate:"
								MDLabel:
									halign: 'right'
									size_hint_y: None
									height: self.texture_size[1]
									text: "Null"
									theme_text_color: 'Custom'
									text_color: 1,0,0,1
									id: mortality_rate
#######################






















								
							
				
			
								
					
			MDGridLayout:
				cols: 1
				padding: 10
				pos_hint: {'top': .25}
				size_hint_y: .1
				MDCard:
					orientation: 'vertical'
	
					size_hint: 1,.02
					
					md_bg_color: 0,0,0,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
					
						text: "Total confirmed ICU:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						
						theme_text_color: 'Custom'
						text_color: 1,0,0,1
						id: total_icu
					
					
					
					
						
					
		Screen:
			name: 'info_screen'
			MDGridLayout:
				cols: 1
				MDCard:
					orientation: 'vertical'
					elevation: 20
					size_hint_y: None
					height: 50
					
					MDLabel:
						text: "ok"
				

		MDScreen:
			name: 'global_screen'
			
			MDGridLayout:
				cols: 1
				padding: 30
				spacing: 20
				pos_hint: {'top':.8}
				size_hint_y: .7
				
				
				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.02
				#	height: self.height
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:

						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
						text: "Total confirmed cases:"
						
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 1,204/255,0,1
						id: global_total
			

				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.02
				#	height: 50
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						

						text: "Total confirmed actives:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 0,102/255,1,1
						id: global_active
						
				
				
				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.02
				#	height: 50
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						

						text: "Total confirmed recovered:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 0, 230/255,77/255,1
						id: global_recovered
		
				
				
				
				
				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.02
				#	height: 50
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						text: "Total confirmed deaths:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 1,0,0,1
						id: global_deaths

		MDScreen:
			name: 'local_screen'
			
			MDGridLayout:
				cols: 1
				padding: 30
				spacing: 20
				pos_hint: {'top':.85}
				size_hint_y: .7
				
				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.5
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
		
						text: "Total confirmed cases:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 255/255,204/255,0,1
						id: total





				MDCard:
					elevation: 10
					orientation: 'vertical'
					size_hint: 1,.5
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
	
						text: "Total confirmed today: "
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 1,0,1,1
						id: total_today
			





				MDCard:
					orientation: 'vertical'
					size_hint: 1,.5
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
		
						text: "Total confirmed actives:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 0,102/255,1,1
						id: active
						
				
				
				MDCard:
					orientation: 'vertical'
					size_hint: 1,.5
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						
		
						text: "Total confirmed recovered:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						theme_text_color: 'Custom'
						text_color: 0, 230/255,77/255,1
						id: recovered
				
				
				
				
				MDCard:
					orientation: 'vertical'
					size_hint: 1,.5
					
					
					md_bg_color: 72/255,72/255,72/255,1
					
					
					MDLabel:
						
						theme_text_color: 'Custom'
						text_color: 1,1,1,1
						

						text: "Total confirmed deaths:"
					MDLabel:
						halign: 'right'
						size_hint_y: None
						height: self.texture_size[1]
						text: "Null"
						
						theme_text_color: 'Custom'
						text_color: 1,0,0,1
						id: deaths
						
						
						
						
		Screen:
			name: 'state_screen'
			MDLabel:
				pos_hint: {'center_y': .85}
				text: "New cases by state"
				halign: 'center'
			MDLabel:
				halign: 'center'
				pos_hint: {'center_x':.5, 'center_y':.5}
				font_size: '30sp'
				id: no_database	
			ScrollView:
				pos_hint: {'top': .8}
				BoxLayout:
					size_hint_y: 2
					orientation: 'vertical'

					MDGridLayout:
						cols: 1
						id: cases_by_states
						
					Widget:
						size_hint_y: .2
		Screen:
			name: 'chart_screen'
			FloatLayout:
				MDLabel:
					pos_hint: {'center_y':.7}
					text: "Chart for 7 days"
					halign: "center"
					id: chart_screen_title
					
					MDCard:
						
						top: chart_screen_title.center_y - 50
						size_hint: None, None
						height: (root.height / 2)
						width: root.width
						id: chart_for_week
						md_bg_color: 0,0,0,1
					


			
						
		
	FloatLayout:
		canvas.before:
			Color:
				rgba: 0,0,0,1
			Rectangle:
				pos: root.pos
				size: root.width, root.height / 10
		
		
		
		MDIconButton:
			user_font_size: '30sp'
			id: dashboard_button
			theme_text_color: 'Custom'
			text_color: 1,1,1,1
			icon: 'view-dashboard-outline'
			id: view-dashboard-outline
			right: root.width / 6
			on_release:
				screen_manager.current = 'global_screen'
				root.highlight_button(0)
		
		MDIconButton:
			user_font_size: '30sp'
			theme_text_color: 'Custom'
			text_color: 1,1,1,1
			icon: 'card-text-outline'
			id: card-text-outline
			right: root.width / 3
			on_release:
				screen_manager.current = 'details_screen'
				root.highlight_button(1)
		
		MDIconButton:
			user_font_size: '30sp'
			theme_text_color: 'Custom'
			text_color: 1,1,1,1
			icon: 'menu'
			id: menu
			right: root.width / 2
			on_release:
				screen_manager.current = 'state_screen'
				root.highlight_button(2)
		
		
		MDIconButton:
			user_font_size: '30sp'
			theme_text_color: 'Custom'
			text_color: 1,1,1,1
			icon: 'chart-line'
			id: chart-line
			right: root.width  / 1.5
			on_release:
				screen_manager.current = 'chart_screen'
				root.highlight_button(3)
		
		
		MDIconButton:
			user_font_size: '30sp'
			theme_text_color: 'Custom'
			text_color: 1,1,1,1
			icon: 'database-refresh'
			id: database-refresh
			right: root.width / 1.2
			on_release:
				screen_manager.current = 'refresh_database'
				root.highlight_button(4)
		


		MDIconButton:
			user_font_size: '30sp'
			theme_text_color: 'Custom'
			text_color: 1,1,1,1
			icon: 'information-outline'
			id: information-outline
			right: root.width
			on_release:
				root.highlight_button(5)
		